### ISSUE TITLE
Make tokenURI adhere to standard & upgradeable

### ISSUE THREAD

**Issue by okwme** [simondlr/artonomous#17]
I noticed the 721 implementation that tokenURI was being used to store the generator hash. I'd suggest the hash be stored in a separate mapping and the tokenURI be made to return a URI that contains all the metadata according to ERC721 spec. I've made an example where that part of the contract can be upgradeable if you think it's useful to use:
https://github.com/okwme/new-models-contracts/blob/master/contracts/Patches.sol
https://github.com/okwme/new-models-contracts/blob/master/contracts/Metadata.sol
tokenURI is delegated to another contract which returns a URI + the tokenId. I have a feeling the tokenURI standard may change in the future so having it upgradeable might be good too.

**Comment by simondlr** [comment]
Solved by #19
